#!/bin/bash

HOST="192.168.1.165"
FILE=$1

egrep -v "changed: \[|ok: \[|skipping: \[|failed: |TASK \[Build |TASK \[Configure|TASK \[Install|TASK \[Remove|TASK \[Clean|TASK \[Autogen|TASK \[Bootstrap|TASK \[Set |${HOST}|PLAY \[HamPi" ${FILE} | grep -P "[0-9]+\.[0-9]+" | grep -Po "[A-Za-z]+ [0-9]+\.[0-9]+\.?[0-9]+"
