#!/bin/bash

egrep -v "changed: \[|ok: \[|skipping: \[|failed: |TASK \[Build |TASK \[Configure|TASK \[Install|TASK \[Remove|TASK \[Clean|TASK \[Autogen|TASK \[Bootstrap|TASK \[Set |192.168.1.228|PLAY \[HamPi" ansible-output_*.txt | grep -P "[0-9]\.[0-9]" | grep -Po "[A-Za-z]+ [0-9]+\.[0-9]+\.?[0-9]?"
