#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install LySDR Software
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/pi/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - autoconf
      - automake
      - autotools-dev
      - libgtk-3-dev
      - libjack-jackd2-dev
      - libfftw3-dev

  - name: Download latest lysdr sources
    git:
      repo: https://github.com/gordonjcp/lysdr.git
      dest: /home/pi/hamradio/lysdr

  - name: Run autoreconf for lysdr
    command: autoreconf -i
    args:
      chdir: /home/pi/hamradio/lysdr

  - name: Configure lysdr
    command: ./configure
    args:
      chdir: /home/pi/hamradio/lysdr

  - name: Build lysdr
    command: make
    args:
      chdir: /home/pi/hamradio/lysdr

  - name: Install lysdr
    become: yes
    command: make install
    args:
      chdir: /home/pi/hamradio/lysdr

  - name: Remove lysdr build directory
    file:
      path: /home/pi/hamradio/lysdr
      state: absent
