name: Run Ansible Playbook

on:
  push:
    branches:
      - master
      - main
      - test

env:
  curdate: ${{ dateFormat(now(), 'YYYY-MM-DD')}}

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts tasks/main.yml | tee --append ansible-output/ansible-output_${curdate}.txt
