name: Run Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run Ansible container
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: |
            ghcr.io/${{ github.repository }}/ansible-runner:latest
      - name: Run Ansible Playbook
        uses: docker/run-action@v3
        with:
          image: ghcr.io/${{ github.repository }}/ansible-runner:latest
